
# Assignment 3 for Course 1MS041
Make sure you pass the `# ... Test` cells and
 submit your solution notebook in the corresponding assignment on the course website. You can submit multiple times before the deadline and your highest score will be used.

---
## Assignment 3, PROBLEM 1
Maximum Points = 8


Download the updated data folder from the course github website or just download directly the file [https://github.com/datascience-intro/1MS041-2024/blob/main/notebooks/data/smhi.csv](https://github.com/datascience-intro/1MS041-2024/blob/main/notebooks/data/smhi.csv) from the github website and put it inside your data folder, i.e. you want the path `data/smhi.csv`. The data was aquired from SMHI (Swedish Meteorological and Hydrological Institute) and constitutes per hour measurements of wind in the Uppsala Aut station. The data consists of windspeed and direction. Your goal is to load the data and work with it a bit. The code you produce should load the file as it is, please do not alter the file as the autograder will only have access to the original file.

The file information is in Swedish so you need to use some translation service, for instance `Google translate` or ChatGPT.

1. [2p] Load the file, for instance using the `csv` package. Put the wind-direction as a numpy array and the wind-speed as another numpy array.
2. [2p] Use the wind-direction which is an angle in degrees and convert it into a point on the unit circle. Store the `x_coordinate` as one array and the `y_coordinate` as another. From these coordinates, construct the wind-velocity vector.
3. [2p] Calculate the average wind velocity and convert it back to direction and compare it to just taking average of the wind direction as given in the data-file.
4. [2p] The wind velocity is a $2$-dimensional random variable, calculate the empirical covariance matrix which should be a numpy array of shape (2,2).

For you to wonder about, is it more likely for you to have headwind or not when going to the university in the morning.

In [ ]:
import numpy as np
import pandas as pd



df = pd.read_csv('data/smhi.csv',skiprows=11, delimiter=';',header = 0)
df.head()

#df = df.drop(['Unnamed: 6',' Time Section:,'], axis = 1)
#print(np.isnan(df[' Wind Speed']).any())  # Check for NaN in wind speed
#print(np.isnan(df[' Wind Direction']).any())  # Check for NaN in wind direction

# Replace NaN with the mean:
# df[' Wind Speed'].fillna(df[' Wind Speed'].mean(), inplace=True)
# df[' Wind Direction'].fillna(df[' Wind Direction'].mean(), inplace=True)

# Remove rows with NaN:
df.dropna(subset=['Vindhastighet','Vindriktning'], inplace=True)
print(df.isnull().sum())

wind_direction = df['Vindriktning'].to_numpy()
wind_speed = df['Vindhastighet'].to_numpy()
print(wind_direction)
print(wind_speed)

print(type(wind_direction))

problem1_wind_direction = wind_direction
problem1_wind_speed = wind_speed


Datum               0
Tid (UTC)           0
Vindriktning        0
Kvalitet            0
Vindhastighet       0
Kvalitet.1          0
Unnamed: 6       3061
Tidsutsnitt:     3048
dtype: int64
[348  43 185 ... 269 281 252]
[0.6 0.2 0.1 ... 1.6 1.4 1.4]
<class 'numpy.ndarray'>


In [3]:

# The wind direction is given as a compass direction in degrees (0-360)
# convert it to x and y coordinates using the standard mathematical convention

wind_direction_rad = np.deg2rad(wind_direction)

x_coordinate = np.cos(wind_direction_rad)
y_coordinate = np.sin(wind_direction_rad)
wind_velocity = np.stack((wind_speed * x_coordinate, wind_speed * y_coordinate), axis=-1)

print(x_coordinate)
print(y_coordinate)
print(wind_velocity)

problem1_wind_direction_x_coordinate = x_coordinate
problem1_wind_direction_y_coordinate = y_coordinate

x_vcoordinates = wind_velocity[:, 0]  # Extract the first column (x-coordinates)
y_vcoordinates = wind_velocity[:, 1]  # Extract the second column (y-coordinates)

problem1_wind_velocity_x_coordinate = x_vcoordinates
problem1_wind_velocity_y_coordinate = y_vcoordinates

print(problem1_wind_velocity_x_coordinate) #To see the output, run the code.
print(problem1_wind_velocity_y_coordinate)  # To see the output, run the code.

[ 0.9781476   0.7313537  -0.9961947  ... -0.01745241  0.190809
 -0.30901699]
[-0.20791169  0.68199836 -0.08715574 ... -0.9998477  -0.98162718
 -0.95105652]
[[ 0.58688856 -0.12474701]
 [ 0.14627074  0.13639967]
 [-0.09961947 -0.00871557]
 ...
 [-0.02792385 -1.59975631]
 [ 0.26713259 -1.37427806]
 [-0.43262379 -1.33147912]]
[ 0.58688856  0.14627074 -0.09961947 ... -0.02792385  0.26713259
 -0.43262379]
[-0.12474701  0.13639967 -0.00871557 ... -1.59975631 -1.37427806
 -1.33147912]


In [5]:

# Put the average wind velocity x and y coordinates here in these variables

average_wind_velocity = np.mean(wind_velocity, axis=0)
print(average_wind_velocity)

average_wind_direction_rad = np.arctan2(average_wind_velocity[1], average_wind_velocity[0])
average_wind_direction_deg = np.rad2deg(average_wind_direction_rad)
print(average_wind_direction_deg)

average_wind_direction_data = np.mean(wind_direction)
print(average_wind_direction_data)

print(f"Average wind direction from velocity: {average_wind_direction_deg:.2f} degrees")
print(f"Average wind direction from data: {average_wind_direction_data:.2f} degrees")

avg_wind_x = average_wind_velocity[0]  # Extract the x-coordinate
avg_wind_y = average_wind_velocity[1]  # Extract the y-coordinate

problem1_average_wind_velocity_x_coordinate = avg_wind_x
problem1_average_wind_velocity_y_coordinate = avg_wind_y


# First calculate the angle of the average wind velocity vector in degrees
problem1_average_wind_velocity_angle_degrees = average_wind_direction_deg
print(problem1_average_wind_velocity_angle_degrees)
# Then calculate the average angle of the wind direction in degrees (using the wind direction in the data)
problem1_average_wind_direction_angle_degrees = average_wind_direction_data
print(problem1_average_wind_direction_angle_degrees)

# Finally, are they the same? Answer as a boolean value (True or False)
problem1_same_angle = False

[-1.0389095  -0.38073122]
-159.87353002120085
192.281280627246
Average wind direction from velocity: -159.87 degrees
Average wind direction from data: 192.28 degrees
-159.87353002120085
192.281280627246


In [9]:
centered_data = wind_velocity - np.mean(wind_velocity, axis=0)  
covariance_matrix = np.cov(centered_data[:, 0], centered_data[:, 1], bias=True)
centered_data.shape

problem1_wind_velocity_covariance_matrix = covariance_matrix

problem1_wind_velocity_covariance_matrix


array([[2.4525164 , 0.06364212],
       [0.06364212, 1.89152174]])

---
## Assignment 3, PROBLEM 2
Maximum Points = 8


For this problem you will need the [pandas](https://pandas.pydata.org/) package and the [sklearn](https://scikit-learn.org/stable/) package. Inside the `data` folder from the course website you will find a file called `indoor_train.csv`, this file includes a bunch of positions in (X,Y,Z) and also a location number. The idea is to assign a room number (Location) to the coordinates (X,Y,Z).

1. [2p] Take the data in the file `indoor_train.csv` and load it using pandas into a dataframe `df_train`
2. [3p] From this dataframe `df_train`, create two numpy arrays, one `Xtrain` and `Ytrain`, they should have sizes `(1154,3)` and `(1154,)` respectively. Their `dtype` should be `float64` and `int64` respectively.
3. [3p] Train a Support Vector Classifier, `sklearn.svc.SVC`, on `Xtrain, Ytrain` with `kernel='linear'` and name the trained model `svc_train`.

To mimic how [kaggle](https://www.kaggle.com/) works, the Autograder has access to a hidden test-set and will test your fitted model.

In [ ]:
import numpy as np
import pandas as pd

df_train= pd.read_csv("data/indoor_train.csv",header = 0)
print(df_train.columns)
df_train.shape

df_train = df_train

df_train.head()

Index(['Position X', ' Position Y', 'Position Z', 'Location'], dtype='object')


Position X   Position Y  Position Z  Location
0        32.0         15.0         4.4        18
1         8.0         17.0         1.5         9
2         4.0         13.0         4.4        13
3        39.0         16.0         4.4        18
4        34.0         12.0         7.6        15

In [15]:

# Xtrain = df_train[['Position X',' Position Y','Position Z']].to_numpy().astype(np.float64)
# Ytrain = df_train['Location'].to_numpy().astype(np.int64)
# Xtrain = df_train.iloc[:,:3].to_numpy().astype(np.float64)
# Ytrain = df_train.iloc[:,3].to_numpy().astype(np.int64)

Xtrain= np.array(df_train.iloc[:,:3]).astype(np.float64)
Ytrain = np.array(df_train.iloc[:,3]).astype(np.int64)

print(Xtrain.shape)  # Output: (1154, 3)
print(Xtrain.dtype) # Output: float64
print(Ytrain.shape)  # Output: (1154,)
print(Ytrain.dtype) # Output: int64


Xtrain = Xtrain
Ytrain = Ytrain


(1154, 3)
float64
(1154,)
int64


In [16]:
from sklearn.svm import SVC

svc_train = SVC(kernel='linear')  # Create an SVC object with a linear kernel
svc_train.fit(Xtrain, Ytrain)  # Train the model using Xtrain and Ytrain

print(svc_train.score(Xtrain,Ytrain))

svc_train = svc_train

0.9965337954939342


---
## Assignment 3, PROBLEM 3
Maximum Points = 8


Let us build a proportional model ($\mathbb{P}(Y=1 \mid X) = G(\beta_0+\beta \cdot X)$ where $G$ is the logistic function) for the spam vs not spam data. Here we assume that the features are presence vs not presence of a word, let $X_1,X_2,X_3$ denote the presence (1) or absence (0) of the words $("free", "prize", "win")$.

1. [2p] Load the file `data/spam.csv` and create two numpy arrays, `problem3_X` which has shape **(n_texts,3)** where each feature in `problem3_X` corresponds to $X_1,X_2,X_3$ from above, `problem3_Y` which has shape **(n_texts,)** and consists of a $1$ if the email is spam and $0$ if it is not. Split this data into a train-calibration-test sets where we have the split $40\%$, $20\%$, $40\%$, put this data in the designated variables in the code cell.

2. [2p] Follow the calculation from the lecture notes where we derive the logistic regression and implement the final loss function inside the class `ProportionalSpam`. You can use the `Test` cell to check that it gives the correct value for a test-point.

3. [2p] Train the model `problem3_ps` on the training data. The goal is to calibrate the probabilities output from the model. Start by creating a new variable `problem3_X_pred` (shape `(n_samples,1)`) which consists of the predictions of `problem3_ps` on the calibration dataset. Then train a calibration model using `sklearn.tree.DecisionTreeRegressor`, store this trained model in `problem3_calibrator`. Recall that calibration error is the following for a fixed function $f$
$$
    \sqrt{\mathbb{E}[|\mathbb{E}[Y \mid f(X)] - f(X)|^2]}.
$$

4. [2p] Use the trained model `problem3_ps` and the calibrator `problem3_calibrator` to make final predictions on the testing data, store the prediction in `problem3_final_predictions`. 

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# Load the data
df = pd.read_csv("data/spam.csv", encoding='latin-1')
#df.columns
#df = df.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis =1)
# Create feature and target arrays
problem3_X = np.zeros((len(df), 3))
problem3_Y = np.zeros(len(df))

for i, row in df.iterrows():
    if 'free' in row['v2'].lower():
        problem3_X[i, 0] = 1
    if 'prize' in row['v2'].lower():
        problem3_X[i, 1] = 1
    if 'win' in row['v2'].lower():
        problem3_X[i, 2] = 1
    if row['v1'] == 'spam':
        problem3_Y[i] = 1

# Split the data
X_train_cal, X_test, Y_train_cal, Y_test = train_test_split(
    problem3_X, problem3_Y, test_size=0.4, random_state=42
)
X_train, X_cal, Y_train, Y_cal = train_test_split(
    X_train_cal, Y_train_cal, test_size=0.25, random_state=42
)  # 0.25 x 0.6 = 0.2

# Print the shapes of the arrays to verify
print("X_train shape:", X_train.shape)
print("Y_train shape:", Y_train.shape)
print("X_cal shape:", X_cal.shape)
print("Y_cal shape:", Y_cal.shape)
print("X_test shape:", X_test.shape)
print("Y_test shape:", Y_test.shape)



problem3_X = problem3_X
problem3_Y = problem3_Y

print(problem3_X,problem3_Y)

problem3_X_train = X_train
problem3_X_calib = X_cal
problem3_X_test = X_test

problem3_Y_train = Y_train
problem3_Y_calib = Y_cal
problem3_Y_test = Y_test

print(problem3_X_train.shape,problem3_X_calib.shape,problem3_X_test.shape,problem3_Y_train.shape,problem3_Y_calib.shape,problem3_Y_test.shape)

X_train shape: (2507, 3)
Y_train shape: (2507,)
X_cal shape: (836, 3)
Y_cal shape: (836,)
X_test shape: (2229, 3)
Y_test shape: (2229,)
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 1.]
 ...
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]] [0. 0. 1. ... 0. 0. 0.]
(2507, 3) (836, 3) (2229, 3) (2507,) (836,) (2229,)


In [41]:


class ProportionalSpam(object):
    def __init__(self):
        self.coeffs = None
        self.result = None
    
    # define the objective/cost/loss function we want to minimise
    def loss(self,X,Y,coeffs):
        import numpy as np
        G = lambda x: np.exp(x)/(1+np.exp(x))
        loss = 0
        for i in range(len(Y)):
            loss += -Y[i]*np.log(G(np.dot(X[i],coeffs[1:])+coeffs[0]))-(1-Y[i])*np.log(1-G(np.dot(X[i],coeffs[1:])+coeffs[0]))
        
        print(loss)
        return loss/2

    def fit(self,X,Y):
        import numpy as np
        from scipy import optimize

        #Use the f above together with an optimization method from scipy
        #to find the coefficients of the model
        opt_loss = lambda coeffs: self.loss(X,Y,coeffs)
        initial_arguments = np.zeros(shape=X.shape[1]+1)
        self.result = optimize.minimize(opt_loss, initial_arguments,method='cg')
        self.coeffs = self.result.x
    
    def predict(self,X):
        #Use the trained model to predict Y
        if (self.coeffs is not None):
            G = lambda x: np.exp(x)/(1+np.exp(x))
            return np.round(10*G(np.dot(X,self.coeffs[1:])+self.coeffs[0]))/10 # This rounding is to help you with the calibration

In [43]:
from sklearn.tree import DecisionTreeRegressor

# Initialize the ProportionalSpam model
problem3_ps = ProportionalSpam()

# Fit the model to the training data
problem3_ps.fit(X_train, Y_train)

# Make predictions on the calibration data
problem3_X_pred = problem3_ps.predict(X_cal)
problem3_X_pred = problem3_X_pred.reshape(-1,1) # Reshape to (n_samples, 1)

# Train a calibration model (DecisionTreeRegressor)
problem3_calibrator = DecisionTreeRegressor()
problem3_calibrator.fit(problem3_X_pred, Y_cal)


problem3_ps = problem3_ps

problem3_X_pred = problem3_X_pred

problem3_calibrator = problem3_calibrator
print(problem3_calibrator)

1737.719981663687
1737.7199953802058
1737.7199811197945
1737.7199813731143
1737.7199815295764
1111.857209093667
1111.8572141321956
1111.8572081312773
1111.8572086707136
1111.8572087204213
1454.4676584959996
1454.4676539416246
1454.46765706068
1454.4676579239529
1454.467657856966
959.9284476305327
959.9284469395953
959.9284464163733
959.9284471235057
959.9284471074706
760.8001450005637
760.8001446913551
760.800144838712
760.8001446277152
760.8001447486545
7693.270955938584
7693.270987184353
7693.270956325992
7693.270955938582
7693.270956326034
754.6354845333985
754.6354847130614
754.6354844416393
754.6354841959391
754.6354843307686
753.372416702104
753.3724172400002
753.3724166551601
753.3724163898272
753.3724165343029
739.9539670344935
739.953967445099
739.9539670102233
739.953966771959
739.9539669160077
714.3727200211395
714.3727200096442
714.3727200741432
714.3727199167478
714.372720071308
743.2089786250967
743.2089789844235
743.2089781434272
743.2089786222494
743.2089784122028
709.8

In [44]:
# Make predictions on the testing data using the trained model
problem3_test_pred = problem3_ps.predict(X_test)
problem3_test_pred = problem3_test_pred.reshape(-1,1) # Reshape to (n_samples, 1)

# Calibrate the predictions using the trained calibrator
problem3_final_predictions = problem3_calibrator.predict(problem3_test_pred)

problem3_final_predictions = problem3_final_predictions
print(problem3_final_predictions)

[0.08914729 0.08914729 0.08914729 ... 0.08914729 0.08914729 0.08914729]


---
#### Local Test for Assignment 3, PROBLEM 3
Evaluate cell below to make sure your answer is valid.                             You **should not** modify anything in the cell below when evaluating it to do a local test of                             your solution.
You may need to include and evaluate code snippets from lecture notebooks in cells above to make the local test work correctly sometimes (see error messages for clues). This is meant to help you become efficient at recalling materials covered in lectures that relate to this problem. Such local tests will generally not be available in the exam.

In [46]:
try:
    import numpy as np
    test_instance = ProportionalSpam()
    test_loss = test_instance.loss(np.array([[1,0,1],[0,1,1]]),np.array([1,0]),np.array([1.2,0.4,0.3,0.9]))
    assert (np.abs(test_loss-1.2828629432232497) < 1e-6)
    print("Your loss was correct  for a test point")
except:
    print("Your loss was not correct on a test point")

2.5657258864465
Your loss was correct  for a test point
